/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectedRouteImport } from './routes/redirected'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeneralSolutionRouteImport } from './routes/_general/solution'
import { Route as GeneralPricingRouteImport } from './routes/_general/pricing'
import { Route as GeneralFeaturesRouteImport } from './routes/_general/features'
import { Route as GeneralAboutRouteImport } from './routes/_general/about'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RedirectedRoute = RedirectedRouteImport.update({
  id: '/redirected',
  path: '/redirected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralSolutionRoute = GeneralSolutionRouteImport.update({
  id: '/_general/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralPricingRoute = GeneralPricingRouteImport.update({
  id: '/_general/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralFeaturesRoute = GeneralFeaturesRouteImport.update({
  id: '/_general/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralAboutRoute = GeneralAboutRouteImport.update({
  id: '/_general/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redirected': typeof RedirectedRoute
  '/account': typeof AuthedAccountRoute
  '/billing': typeof AuthedBillingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/about': typeof GeneralAboutRoute
  '/features': typeof GeneralFeaturesRoute
  '/pricing': typeof GeneralPricingRoute
  '/solution': typeof GeneralSolutionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redirected': typeof RedirectedRoute
  '/account': typeof AuthedAccountRoute
  '/billing': typeof AuthedBillingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/about': typeof GeneralAboutRoute
  '/features': typeof GeneralFeaturesRoute
  '/pricing': typeof GeneralPricingRoute
  '/solution': typeof GeneralSolutionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redirected': typeof RedirectedRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_general/about': typeof GeneralAboutRoute
  '/_general/features': typeof GeneralFeaturesRoute
  '/_general/pricing': typeof GeneralPricingRoute
  '/_general/solution': typeof GeneralSolutionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redirected'
    | '/account'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/about'
    | '/features'
    | '/pricing'
    | '/solution'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redirected'
    | '/account'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/about'
    | '/features'
    | '/pricing'
    | '/solution'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/redirected'
    | '/_authed/account'
    | '/_authed/billing'
    | '/_authed/dashboard'
    | '/_authed/notifications'
    | '/_general/about'
    | '/_general/features'
    | '/_general/pricing'
    | '/_general/solution'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedirectedRoute: typeof RedirectedRoute
  GeneralAboutRoute: typeof GeneralAboutRoute
  GeneralFeaturesRoute: typeof GeneralFeaturesRoute
  GeneralPricingRoute: typeof GeneralPricingRoute
  GeneralSolutionRoute: typeof GeneralSolutionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirected': {
      id: '/redirected'
      path: '/redirected'
      fullPath: '/redirected'
      preLoaderRoute: typeof RedirectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/solution': {
      id: '/_general/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof GeneralSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/pricing': {
      id: '/_general/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof GeneralPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/features': {
      id: '/_general/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof GeneralFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/about': {
      id: '/_general/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GeneralAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedirectedRoute: RedirectedRoute,
  GeneralAboutRoute: GeneralAboutRoute,
  GeneralFeaturesRoute: GeneralFeaturesRoute,
  GeneralPricingRoute: GeneralPricingRoute,
  GeneralSolutionRoute: GeneralSolutionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
