import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_general/about')({
  component: RouteComponent,
})

function RouteComponent() {
  return <><div className="mb-4 space-y-2"><div className="h-6 w-4/6 rounded-md border bg-accent"></div><div className="h-6 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 flex gap-2"><div className="h-3 w-14 rounded-md border bg-accent"></div><div className="h-3 w-12 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div><div className="mb-8 space-y-2"><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-full rounded-md border bg-accent"></div><div className="h-4 w-1/2 rounded-md border bg-accent"></div></div></>
}
